# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 4
name = "Lessons"
hasChildren = true

[[main]]
parent = "Lessons"
name = "All lessons"
url = "lessons/"
weight = 1


[[main]]
parent = "Lessons"
name = "Intro to git"
url = "/git-intro/"
weight = 3

[[main]]
parent = "Lessons"
name = "Install Python"
url = "/install-python-science-conda/"
weight = 4

[[main]]
parent = "Lessons"
name = "Functions in Python"
url = "/write-functions/"
weight = 4

# [[main]]
# parent = "Lessons"
# name = "About"
# url = "about/"
# weight = 5
# [[main]]
# parent = "Lessons"
# name = "Team"
# url = "team/"
# weight = 4

# [[main]]
# parent = "Lessons"
# name = "How It Works"
# url = "how-it-works/"
# weight = 8

# [[main]]
# parent = "Lessons"
# name = "Career"
# url = "career/"
# weight = 9

# [[main]]
# parent = "Lessons"
# name = "Career Details"
# url = "career/sr-executive-service-assurance/"
# weight = 10

[[main]]
weight = 6
name = "Partners"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Partners"
name = "pyOpenSci"
pre = "<i class='dropdown-icon fas fa-users'></i>"
post = "<small class='dropdown-subtitle'>We build diverse community around the open source tools that drive open science.</small>"
url = "partners/pyopensci/"
weight = 1

# [[main]]
# parent = "Partners"
# name = "Help Desk"
# pre = "<i class='dropdown-icon fas fa-dice-d6'></i>"
# post = "<small class='dropdown-subtitle'>Software to deliver great customer support.</small>"
# url = "partners/product-2/"
# weight = 2

# [[main]]
# parent = "Partners"
# name = "Workplace"
# pre = "<i class='dropdown-icon fas fa-laptop-house'></i>"
# post = "<small class='dropdown-subtitle'>Application built to improve productivity.</small>"
# url = "partners/product-3/"
# weight = 3

# [[main]]
# parent = "Partners"
# name = "Analytics"
# pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
# post = "<small class='dropdown-subtitle'>Create custom reports from any data set.</small>"
# url = "partners/product-4/"
# weight = 4

# [[main]]
# parent = "Partners"
# name = "View All Product"
# pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
# url = "partners/"
# weight = 5

# [[main]]
# weight = 13
# name = "Blog"
# hasChildren = true

# [[main]]
# parent = "Blog"
# name = "Blog Posts"
# url = "blog/"
# weight = 3

# [[main]]
# parent = "Blog"
# name = "Blog Details"
# url = "blog/post-1/"
# weight = 8

# [[main]]
# parent = "Blog"
# name = "Author"
# url = "author/"
# weight = 11

# [[main]]
# parent = "Blog"
# name = "Author Details"
# url = "author/awab-husameldin/"
# weight = 12

# [[main]]
# weight = 15
# name = "Pages"
# hasChildren = true

# [[main]]
# parent = "Pages"
# name = "Pricing"
# url = "pricing/"
# weight = 1

# [[main]]
# parent = "Pages"
# name = "Case Studies"
# url = "case-studies/"
# weight = 4

# [[main]]
# parent = "Pages"
# name = "Case Studies Details"
# url = "case-studies/case-1/"
# weight = 5

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"
# weight = 10

# [[main]]
# parent = "Pages"
# name = "FAQ"
# url = "faq/"
# weight = 16

# [[main]]
# parent = "Pages"
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 20

# [[main]]
# parent = "Pages"
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 24

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 30

# # footer menu left
# [[footer_left]]
# name = "About Us"
# url = "about/"
# weight = 1

# [[footer_left]]
# name = "Team"
# url = "team/"
# weight = 2

# [[footer_left]]
# name = "How It Works"
# url = "how-it-works/"
# weight = 3

# [[footer_left]]
# name = "Career"
# url = "career/"
# weight = 4


# # footer menu middle
# [[footer_middle]]
# name = "CRM"
# url = "partners/product-1/"
# weight = 1

# [[footer_middle]]
# name = "Help Desk"
# url = "partners/product-2/"
# weight = 2

# [[footer_middle]]
# name = "Workplace"
# url = "partners/product-3/"
# weight = 3

# [[footer_middle]]
# name = "Analytics"
# url = "partners/product-4/"
# weight = 4

# # footer menu right
# [[footer_right]]
# name = "FAQ"
# url = "faq/"
# weight = 1

# [[footer_right]]
# name = "Contact"
# url = "contact/"
# weight = 2

# [[footer_right]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[footer_right]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 4
