name: dataskills
channels:
  - conda-forge

dependencies:
  - python=3.10
  # Core scientific python
  - numpy

  # Plotting
  - matplotlib
  - bokeh

  # Jupyter
  - jupyterlab
  - notebook

  # Infra
  - watchdog
  - nox
