name: Build DSS website
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    container: leahawasser/dss-mamba
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check versions
        run: |
          quarto --version
          which python
          mamba list

      - name: Render website
        run: |
          quarto render
          ls

      # Push the book's HTML to github-pages
      - name: Push to GitHub Pages
        # Only push if on main branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dsk/_site
